package com.streamvault.app.features.profiles

object NetflixAvatars {
    val DEFAULT_CATALOG: List<AvatarCatalogItem> = listOf(
        AvatarCatalogItem(
            id = "netflix-classic-1",
            displayName = "Netflix Classic #1",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTtzfQn_TnlmI0dXn5jkfRFxmK1cjkW0zvz_qkvE4MT05lZLOhPuyHXGLF4EaOKu7aYlkrYf3X_a_af3ubt2_hek8y0rYcVBbw.png?r=181",
            sortOrder = 1,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-2",
            displayName = "Netflix Classic #2",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbBdWEzsqtpcYRfW0oClQ8jdJx6uHK5oNiHQPNZrUhrT5-2gizvuV0zRpgYoXI-hS7JqdZ1Q_mCWUUWlaNx4pHv1c__GSpT8Gg.png?r=cad",
            sortOrder = 2,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-3",
            displayName = "Netflix Classic #3",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSn2_6LFL85K2778XevmpMlKrQdbxP8sDwZtd2J3rQbp9DHH4pSvtfhbDmiFQb1MYo1BP1bfbiswS36yZAT0lrAGEAdL2-fxxA.png?r=ce4",
            sortOrder = 3,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-4",
            displayName = "Netflix Classic #4",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTRWEBsHFNtCYoz5JbkqcXzqV_7Av6U_fWbAdlLgm9t2ZyLXTeug7cbasJzeK5KfCUNTpDFGzgflkMUJQ7zRH_eunGhccGJGxg.png?r=201",
            sortOrder = 4,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-5",
            displayName = "Netflix Classic #5",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaB4hP-03hFOdIwXeYrc_Fb0P-QukEb4sV2BnOlJKVG1dpjJpL7aUOu4VFZenH1zr20DMYE6e8Fa6E7L9BnCvKlDzZEd25S_Ew.png?r=7c7",
            sortOrder = 5,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-6",
            displayName = "Netflix Classic #6",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTzykXqE0IgG15a8RLZ7okU8HrL3PU7kuNVL91w9HjwJXRswlPVKSVvVdYUSoea9F1CONTUIZyRzxpgZFd0XC94v-svyKCQpXA.png?r=b39",
            sortOrder = 6,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-7",
            displayName = "Netflix Classic #7",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfV378_nLCLJYYUS14ujtntA1bLSp4VseVCuahmhQGGoWVOwxuuqGAmICG3H5L-24Fvh8Ezkj6Fik4F9jMGbFitqsfnFrDVh6Q.png?r=6a6",
            sortOrder = 7,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-8",
            displayName = "Netflix Classic #8",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRp8SIY8MrmT39ab3mMLfmQJXbqadfYfBgxgiHOicZRcQiKKGzofuF30ttGIfs16m6IJZESxa4-o-LToGAhonn69QkSRrfh1mg.png?r=558",
            sortOrder = 8,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-9",
            displayName = "Netflix Classic #9",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbLEEun9sRrpMu7Ubarx34UxX2F8e5pLgdmQ8Z9Ah9BMMgdy9Q_5NxVa--nuZ9pWmepc98T6ww7H5UsjC3dFDTUD7YAnOgoArA.png?r=a16",
            sortOrder = 9,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-10",
            displayName = "Netflix Classic #10",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbLEEun9sRrpMu7Ubarx34UxX2F8e5pLgdmQ8Z9Ah9BMMgdy9Q_5NxVa--nuZ9pWmepc98T6ww7H5UsjC3dFDTUD7YAnOgoArA.png?r=a16",
            sortOrder = 10,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-11",
            displayName = "Netflix Classic #11",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYQm8gxRTmSri9n9-XbbfDZFfaKL5cuJk6qCjQ_yYs72QVu2hLI-ZbEwI3zQiNOHT0MUdhFnvJkt3v8HBxOPg086xIDsMxyAtw.png?r=d47",
            sortOrder = 11,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-12",
            displayName = "Netflix Classic #12",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVe7TgSyaY711GsMBuILmT5OnGkxSxE4WT13On1uT0a_yYTsRY7VyG-Kd2j2pGeFp4mTaFYKXmxazizqjMGpu4Hj76sjePAipw.png?r=ae9",
            sortOrder = 12,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-13",
            displayName = "Netflix Classic #13",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYPTk-lJwL8jeVZoJJUHDBCBKTOHvq52XpkgHAXGAI9tzk5eUGy373181Xuqtz727B_VDlO-MyIgxFGKFDKYryKJgLCfi9dWaQ.png?r=ab6",
            sortOrder = 13,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-14",
            displayName = "Netflix Classic #14",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZYoflVXvpbUIpSWMQS9FHelYN9Ng7ZfpmQpnQ6MkleFgoXcmq_TJVuzN78OrfyOyHiNsvrrlwUdVnOUM9JQrJ6f6Zy-z2UpMg.png?r=bb0",
            sortOrder = 14,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-15",
            displayName = "Netflix Classic #15",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUkvOCLpzPdTWJZAa0ntjneGlRbwVD_29llzq6-Iw2HgXHqWEVDuxs9EYQhtIjze6g5QNjxKyLtVgWosZ7b-b5zo6Q4sRNN_rg.png?r=59d",
            sortOrder = 15,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-16",
            displayName = "Netflix Classic #16",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABdgFndjYdBrqj3q386A40uOa6308UTPkyNQjDFJ-aUQQrk7hqmLD7jotC59fAwnOs78kLMGBxLWMRevfcsnOjU1d_kvoZC6Fdg.png?r=15e",
            sortOrder = 16,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-17",
            displayName = "Netflix Classic #17",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABakRc13qnznu9gXCjeNTetIpWLBYv1BHtjenkcA2UPHsk_oKNyiEjMqDg5JrLMa6B-Ynairtq2_fSFPjKJ6mqB2xuIeeCZm23A.png?r=e6e",
            sortOrder = 17,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-18",
            displayName = "Netflix Classic #18",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTfUlmnFRKf_OEUhru2aqso39FKxONTd5Dt_sWnNj5wAg4bbMBZ8sgZupTfnB9IQ8tmWcrzRiyZsCp1bLKb_n7VrnTw3_Ovw7Q.png?r=bd7",
            sortOrder = 18,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-19",
            displayName = "Netflix Classic #19",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABelkMs-h2DXUYbzHHCaFQo7ykBvO6JoCssR5azSK1jNcUTRExSzh9R1HNbNbWzIhTri5iN8U3N9GSmbXeLASZqL5IKRHLri1PA.png?r=1d4",
            sortOrder = 19,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-20",
            displayName = "Netflix Classic #20",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXan2ftdVhTtVVzZctW_PhUGLw-uzzdXn1BaTkNyVzJQk62yuNZpVU0_GUBJu9X6ry23mg6k7-C11lblVvDFot41ZZ6dxcZoFw.png?r=a4b",
            sortOrder = 20,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-21",
            displayName = "Netflix Classic #21",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVhab2XqRI6ThDSR6UvGIb_4U4tDnYLNtsDTaZxg91Vj02LwK50_WVhohDm7wDZ_ncQP7D9EQo_iPdzQDCU7ulekO9gcgOMKDw.png?r=98e",
            sortOrder = 21,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-22",
            displayName = "Netflix Classic #22",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABedBXQ7LUp91euJT4qzL6i6X6ZK0DUt9o_tXOojv1XvPtAifsQWvcOd2Z6vFM7wdgXCo1m_DPiJTzInm0Lbo2oABEeAaAxOWJQ.png?r=54c",
            sortOrder = 22,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-23",
            displayName = "Netflix Classic #23",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXh10ggeTTdhZO1JIH_SNQ4gp0vsNnWfE8Mg2ckwzGvUzJMRpPFCujRK3Ex5K9VbkIyvUHQ92LBVdsemkj6zlpquL-qWMCNKeg.png?r=229",
            sortOrder = 23,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-24",
            displayName = "Netflix Classic #24",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTtzfQn_TnlmI0dXn5jkfRFxmK1cjkW0zvz_qkvE4MT05lZLOhPuyHXGLF4EaOKu7aYlkrYf3X_a_af3ubt2_hek8y0rYcVBbw.png?r=181",
            sortOrder = 24,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-25",
            displayName = "Netflix Classic #25",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbBdWEzsqtpcYRfW0oClQ8jdJx6uHK5oNiHQPNZrUhrT5-2gizvuV0zRpgYoXI-hS7JqdZ1Q_mCWUUWlaNx4pHv1c__GSpT8Gg.png?r=cad",
            sortOrder = 25,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-26",
            displayName = "Netflix Classic #26",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSn2_6LFL85K2778XevmpMlKrQdbxP8sDwZtd2J3rQbp9DHH4pSvtfhbDmiFQb1MYo1BP1bfbiswS36yZAT0lrAGEAdL2-fxxA.png?r=ce4",
            sortOrder = 26,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-27",
            displayName = "Netflix Classic #27",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTRWEBsHFNtCYoz5JbkqcXzqV_7Av6U_fWbAdlLgm9t2ZyLXTeug7cbasJzeK5KfCUNTpDFGzgflkMUJQ7zRH_eunGhccGJGxg.png?r=201",
            sortOrder = 27,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-28",
            displayName = "Netflix Classic #28",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaB4hP-03hFOdIwXeYrc_Fb0P-QukEb4sV2BnOlJKVG1dpjJpL7aUOu4VFZenH1zr20DMYE6e8Fa6E7L9BnCvKlDzZEd25S_Ew.png?r=7c7",
            sortOrder = 28,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-29",
            displayName = "Netflix Classic #29",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTzykXqE0IgG15a8RLZ7okU8HrL3PU7kuNVL91w9HjwJXRswlPVKSVvVdYUSoea9F1CONTUIZyRzxpgZFd0XC94v-svyKCQpXA.png?r=b39",
            sortOrder = 29,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-30",
            displayName = "Netflix Classic #30",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfV378_nLCLJYYUS14ujtntA1bLSp4VseVCuahmhQGGoWVOwxuuqGAmICG3H5L-24Fvh8Ezkj6Fik4F9jMGbFitqsfnFrDVh6Q.png?r=6a6",
            sortOrder = 30,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-31",
            displayName = "Netflix Classic #31",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRp8SIY8MrmT39ab3mMLfmQJXbqadfYfBgxgiHOicZRcQiKKGzofuF30ttGIfs16m6IJZESxa4-o-LToGAhonn69QkSRrfh1mg.png?r=558",
            sortOrder = 31,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-32",
            displayName = "Netflix Classic #32",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbLEEun9sRrpMu7Ubarx34UxX2F8e5pLgdmQ8Z9Ah9BMMgdy9Q_5NxVa--nuZ9pWmepc98T6ww7H5UsjC3dFDTUD7YAnOgoArA.png?r=a16",
            sortOrder = 32,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-33",
            displayName = "Netflix Classic #33",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbLEEun9sRrpMu7Ubarx34UxX2F8e5pLgdmQ8Z9Ah9BMMgdy9Q_5NxVa--nuZ9pWmepc98T6ww7H5UsjC3dFDTUD7YAnOgoArA.png?r=a16",
            sortOrder = 33,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-34",
            displayName = "Netflix Classic #34",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYQm8gxRTmSri9n9-XbbfDZFfaKL5cuJk6qCjQ_yYs72QVu2hLI-ZbEwI3zQiNOHT0MUdhFnvJkt3v8HBxOPg086xIDsMxyAtw.png?r=d47",
            sortOrder = 34,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-35",
            displayName = "Netflix Classic #35",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVe7TgSyaY711GsMBuILmT5OnGkxSxE4WT13On1uT0a_yYTsRY7VyG-Kd2j2pGeFp4mTaFYKXmxazizqjMGpu4Hj76sjePAipw.png?r=ae9",
            sortOrder = 35,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-36",
            displayName = "Netflix Classic #36",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYPTk-lJwL8jeVZoJJUHDBCBKTOHvq52XpkgHAXGAI9tzk5eUGy373181Xuqtz727B_VDlO-MyIgxFGKFDKYryKJgLCfi9dWaQ.png?r=ab6",
            sortOrder = 36,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-37",
            displayName = "Netflix Classic #37",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZYoflVXvpbUIpSWMQS9FHelYN9Ng7ZfpmQpnQ6MkleFgoXcmq_TJVuzN78OrfyOyHiNsvrrlwUdVnOUM9JQrJ6f6Zy-z2UpMg.png?r=bb0",
            sortOrder = 37,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-38",
            displayName = "Netflix Classic #38",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUkvOCLpzPdTWJZAa0ntjneGlRbwVD_29llzq6-Iw2HgXHqWEVDuxs9EYQhtIjze6g5QNjxKyLtVgWosZ7b-b5zo6Q4sRNN_rg.png?r=59d",
            sortOrder = 38,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-39",
            displayName = "Netflix Classic #39",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABdgFndjYdBrqj3q386A40uOa6308UTPkyNQjDFJ-aUQQrk7hqmLD7jotC59fAwnOs78kLMGBxLWMRevfcsnOjU1d_kvoZC6Fdg.png?r=15e",
            sortOrder = 39,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-40",
            displayName = "Netflix Classic #40",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABakRc13qnznu9gXCjeNTetIpWLBYv1BHtjenkcA2UPHsk_oKNyiEjMqDg5JrLMa6B-Ynairtq2_fSFPjKJ6mqB2xuIeeCZm23A.png?r=e6e",
            sortOrder = 40,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-41",
            displayName = "Netflix Classic #41",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTfUlmnFRKf_OEUhru2aqso39FKxONTd5Dt_sWnNj5wAg4bbMBZ8sgZupTfnB9IQ8tmWcrzRiyZsCp1bLKb_n7VrnTw3_Ovw7Q.png?r=bd7",
            sortOrder = 41,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-42",
            displayName = "Netflix Classic #42",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABelkMs-h2DXUYbzHHCaFQo7ykBvO6JoCssR5azSK1jNcUTRExSzh9R1HNbNbWzIhTri5iN8U3N9GSmbXeLASZqL5IKRHLri1PA.png?r=1d4",
            sortOrder = 42,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-43",
            displayName = "Netflix Classic #43",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXan2ftdVhTtVVzZctW_PhUGLw-uzzdXn1BaTkNyVzJQk62yuNZpVU0_GUBJu9X6ry23mg6k7-C11lblVvDFot41ZZ6dxcZoFw.png?r=a4b",
            sortOrder = 43,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-44",
            displayName = "Netflix Classic #44",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVhab2XqRI6ThDSR6UvGIb_4U4tDnYLNtsDTaZxg91Vj02LwK50_WVhohDm7wDZ_ncQP7D9EQo_iPdzQDCU7ulekO9gcgOMKDw.png?r=98e",
            sortOrder = 44,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-45",
            displayName = "Netflix Classic #45",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABedBXQ7LUp91euJT4qzL6i6X6ZK0DUt9o_tXOojv1XvPtAifsQWvcOd2Z6vFM7wdgXCo1m_DPiJTzInm0Lbo2oABEeAaAxOWJQ.png?r=54c",
            sortOrder = 45,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-classic-46",
            displayName = "Netflix Classic #46",
            category = "Classics",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXh10ggeTTdhZO1JIH_SNQ4gp0vsNnWfE8Mg2ckwzGvUzJMRpPFCujRK3Ex5K9VbkIyvUHQ92LBVdsemkj6zlpquL-qWMCNKeg.png?r=229",
            sortOrder = 46,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-1",
            displayName = "Stranger Things #1",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWWI3W8XrttCXs-Pq9j8sgOuRWRvmRAF5CepVYdMYM-xFDK_cQ9V0wM6W22lmHuOUyel_WTZitjX9GFxAFAOVeX24V-ANkH8Ww.png?r=d32",
            sortOrder = 47,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-2",
            displayName = "Stranger Things #2",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRBaAcLik2wEJVkgAnuGfMzEHeTl2bRo7hDUtas_nFa_Sk5jGNvA8jWZE3nRn9qTMyh341ldGwYWZCyYxitTn3Ga2WvEvvnulw.png?r=df8",
            sortOrder = 48,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-3",
            displayName = "Stranger Things #3",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQyyBznLc9trefnRqqBbDG-afrAENJJTa4E_fAEL80CG8SH9CJruWXj_dOgzLjpfYhk3vVqoZX_sKiuVb-mve1TsxoVIwWym9g.png?r=9f9",
            sortOrder = 49,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-4",
            displayName = "Stranger Things #4",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWz26XLp1SeMbmnT5zNbBKn6byYE2i2xcepdKuPwtv_owGymD5lblwCd0UN4ld9f_YmuQIgsqp4BbO-2-sIyGjSxcdbDBrY6YQ.png?r=d43",
            sortOrder = 50,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-5",
            displayName = "Stranger Things #5",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABd40j3GNUUbA7LCsQBphIIUsZ3SYZV047x45wzr8wFI4y_4hYTz7kqn1-xR7cAG3yEj7Q70Nqy8lZuXLWtuxVhEE5P-dcgbDiQ.png?r=613",
            sortOrder = 51,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-6",
            displayName = "Stranger Things #6",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXgCiVt2QEjISSnelKrPj7zSpJ3XlDz6HjpP8GFbZSOcrBVEKqdRiHrOaYZohDT13hl6DyG5os7u3CJK9sBivU4FJkMHne3Wgw.png?r=f52",
            sortOrder = 52,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-7",
            displayName = "Stranger Things #7",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUB43hN66c4Lt-saxjJRq8lket2G9-WXD-Kqcl_leo0wHuxWkxkQAOVu_ZMHncH-CJ05N1SNq1_1sPJ2VsmRZnzEhglb4K1u-A.png?r=934",
            sortOrder = 53,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-stranger-things-8",
            displayName = "Stranger Things #8",
            category = "Stranger Things",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABW6HXqFKoVZf1bk7i1fAnuFUkFWbwtMfwlfsDg4UEu8by0x2mGows1xz3gcRmIgGIJNl3I1Nz9vdp9ysTDmnbo04oPmxL1Bh_Q.png?r=e66",
            sortOrder = 54,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-1",
            displayName = "Squid Game #1",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWVoYzlSivjXDh16yJtaZ2BJ11T4Tnjuu2ODGqzGHaMvGliRQgaQrroMgVMDfXtlp9QKPYSKIWHIGjU83kcCpksI43rFWcus8g.png?r=83b",
            sortOrder = 55,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-2",
            displayName = "Squid Game #2",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYi8u2Nz9dp3EF_xcUQoW4TbnDi672S6usNUHhola5qHBSVEhNnIG8FadHiWs_L985TvUX7ST9m7CijuBJqeoO5oHirnkPkNYw.png?r=66c",
            sortOrder = 56,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-3",
            displayName = "Squid Game #3",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfPu2f1oZJ0FZdVC4ZppMaGFIZb1ACzzzlfHVDL_mt7IL6CIXRBkG25MwaF0odM6YCMBU8YVV_NAT9dP-r9Wv_3ttFb3hEAJvQ.png?r=d38",
            sortOrder = 57,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-4",
            displayName = "Squid Game #4",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVAT9O2xslNGonW6i6hvuphcgvqG5pWL0pPTNGmI-aBBq9xpfcWRUwqPYd4W1EOycE6VhKEZAGmKU1miGeUG9toxfuwwG2Grig.png?r=0b0",
            sortOrder = 58,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-5",
            displayName = "Squid Game #5",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYF8dGeSMi9OTFGFtVt8LrkNh3KcVLQRddt3RbyJOx_36oG_Y0UGr-PZb6_4sCyVdNLQzfgcHQTZhLDTJJKQsujCNWWxgr8vRw.png?r=53d",
            sortOrder = 59,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-6",
            displayName = "Squid Game #6",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaf6bSDyuyhRZZHghjl4WRiwDGNwrUMm0ubhzGazAQZ3pKwXt8qCqCRnYi_qPsudjMP-NjV6SUbUHZjMzyrojHHyhZxTS0LsmQ.png?r=221",
            sortOrder = 60,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-7",
            displayName = "Squid Game #7",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbHegk9qgxy88EPIqoCR8RV_jyjvaJetZBUkWRokvF5OE-J7giTRUzV2wPZ3J9XHV5LAU_tCuWGwcfg_jPjEJzKwcVtq-uu9GQ.png?r=7a7",
            sortOrder = 61,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-squid-game-8",
            displayName = "Squid Game #8",
            category = "Squid Game",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYbrqdf7I4CYwyJH8YDRuWVX1wkNsxDXQpd3b3VO_My7_6_GL8g_r_kUC_dVstGYx5IQU5VK6xyysrHdPmampfcc56x_wT8HCg.png?r=c83",
            sortOrder = 62,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-1",
            displayName = "Wednesday #1",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABS_fCAimFcSuIgnyvchWA3eNUjEsCsciKhhXfklGV3idvRbG7qu7YwPOCIyNrZNjkteloppY2M-9rXnuvUYXPqTIXh5GB9Ri_Q.png?r=02d",
            sortOrder = 63,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-2",
            displayName = "Wednesday #2",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSXPwEmF1ALowNekM3-Uwn3C6sxfRrMDcs4b8KnmNQXc23gv5kjjYSnQEZvKtRN7RvnXVk-ynPqT_LTIeKqiBUOc-v06PRlbVQ.png?r=6c2",
            sortOrder = 64,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-3",
            displayName = "Wednesday #3",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbidUu_tkyyAjZStpacpzss9f9-AeQCA9AJ7DRNHWU8gAsyINSmH78P3ZUWPJi9p70BxmVlYGHIWmtro2yHtounkoayo2l3_vg.png?r=70b",
            sortOrder = 65,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-4",
            displayName = "Wednesday #4",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQJZ8ma4sAR9THPLaaT0Ymm3-Vq1aQSGNu9B891G9BRBUYRPFY8vbLUcp_zRxUyNdDMTdLgqkwmWZk0aIxdIlxoaD6MuaYkgmg.png?r=fff",
            sortOrder = 66,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-5",
            displayName = "Wednesday #5",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTLZj0uwbm7xUAiqmyK1hsMyiQWZLhaMM7yg0YhTO7EJKaCKA_g-xAIWwWzZKNKHLbCx6RupWw9u7enfPOveA7UKo1HPzxaZKQ.png?r=421",
            sortOrder = 67,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-6",
            displayName = "Wednesday #6",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWJTugBIKI6XqzBJTtniPoW3zv0_e8c7fiulfIk5h-CJ_ievAQ8FBIiKiEwCJ3akxzZZoVgVcAsSX_lcxEbnt7w3V6L9o848cQ.png?r=ae0",
            sortOrder = 68,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-7",
            displayName = "Wednesday #7",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRkRJHSCaKv8Y8Ctkmu2NhzLOHgVhI0xNTj0VZuoxWIFRAVJCmaYMpiuzb7hlINAzlwLtYAkHfas4HWoK4IMAs4z89sYzY_FhA.png?r=a83",
            sortOrder = 69,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-wednesday-8",
            displayName = "Wednesday #8",
            category = "Wednesday",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbphDMErQOrG7kJt8DbEge3HkyhX38NIERMnDnuWGxB7kKtkX_99YnO5h1stYhsam7AtAkHjQZ-x9_WNdq3xDMv-1FPD87N8Ww.png?r=f26",
            sortOrder = 70,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-1",
            displayName = "Arcane: League of Legends #1",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaSX2NqfYXqDB_Z33yOHnpIiTcBqMDAEzIl4lYXzhlFB16oLyY4P0Vy0IdAZgSH926Z7vwuXhWa3U2ZeutsSPpEYfX2LyyGtOg.png?r=87b",
            sortOrder = 71,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-2",
            displayName = "Arcane: League of Legends #2",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQvEeRlO6uh4Ltrr6A88A1_ZzmDYXBpNLQtrfaC_JerFQ1EyU0r_swymIEoF1U6dZIBepb1_y1qvlWG7jPmzdORFh1w6mSYkPQ.png?r=e31",
            sortOrder = 72,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-3",
            displayName = "Arcane: League of Legends #3",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQdzyJ2Un-NhhiXmyLgTgXGOGliBwzmPr7U9DEeF83M8WLMQbjC9s2tVR60x8ngQ6gFBAPHoo7ddOupjPr1ZgShlKdn83yn62A.png?r=375",
            sortOrder = 73,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-4",
            displayName = "Arcane: League of Legends #4",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQMIrtIGZuK6nd_xSsq_VisWrmiP3JY5og-IUazwMvBYuWFdiJXPZnbVLjyQ-mn3KjjaYwzBgOJLPTSqg9d-OwQPBKBTyMuHrQ.png?r=2da",
            sortOrder = 74,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-5",
            displayName = "Arcane: League of Legends #5",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaP2UtcdywvAI_lVC-GQd8uN5PzAWVvj_QrTfeQTXZWuPrNu8B7gPb2xUdB8nadBg4Nqw4rHDY6rA_j3RsA8KK5GvAgMKJ4RUg.png?r=725",
            sortOrder = 75,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-6",
            displayName = "Arcane: League of Legends #6",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRjz4P_ojPCKK-fQcL6PiG9dZH9JTRwicLha2KZZjpNita3wC1esEc3r-hxETe5rJgwO7b7Iqge8ZBnCPGPhcIxxmfHA0DTBLQ.png?r=5f0",
            sortOrder = 76,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-7",
            displayName = "Arcane: League of Legends #7",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaNN3AwLTQSoIIXF44uhS3BHLoGAHYQoagbzZp9mp0Uq4wNVnADJ0dvLaQ1965xiTX5vaspCn_lZ5rMI6hDEeKO5xeu4PMG6GQ.png?r=a21",
            sortOrder = 77,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-arcane--league-of-legends-8",
            displayName = "Arcane: League of Legends #8",
            category = "Arcane: League of Legends",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQYh98qv-HviM-CKyns0-hQ_ocSQRbg2Qd-1ILs75Q2EWAgY8Og4LrwtzIcfI5c2Z9m4XWofBThxhwNVENg59wHZqe1JMQODQg.png?r=a4f",
            sortOrder = 78,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-1",
            displayName = "Money Heist #1",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZIN5ALWTmxTEQzWlyqBhHzRBeBtVN-FpWudf6fgrghnio_-XZIbS3jdQ0abnzMFN1VwaKHm8j4Wj3G7iw-_s2VOuzI0rmTfig.png?r=852",
            sortOrder = 79,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-2",
            displayName = "Money Heist #2",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQPQcU0ckecAwbr6vEDlu2l5UawW6M82K7Sgx2dgpj9XIUW9sSJosAXvp2l_1hTdCxCEs9uFwyfYXgW-BrN-qDBNtTND3rmrlw.png?r=d0a",
            sortOrder = 80,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-3",
            displayName = "Money Heist #3",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWrhs_UHEmhWXUmtn2KzQ_ILxSeBreYN0kRAb-A5KNC0vzzOO7LEBUUx0AtTDHmr3hHTxKGWb4bmZ9CP0_iWzyFsQA0Tx-FSig.png?r=d19",
            sortOrder = 81,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-4",
            displayName = "Money Heist #4",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYqQWXH98Pzf8msDpV2poLCKqSG4BOt4NoHMH-R6s0HYdbbXbUelr9AjwvYRiLT6p9bNQQNeIICa3d-Hsgyr663l-9aQaR1VTg.png?r=b38",
            sortOrder = 82,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-5",
            displayName = "Money Heist #5",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRuAr7gdlNTAcZRY8LvQE3VdtSePvpRer05xVD-aB9jDx-4eYSaGRa42fvuJDGduWiJ4nlNH_5IbRyTMqZQQeMShG0qyGPXVsw.png?r=b0f",
            sortOrder = 83,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-6",
            displayName = "Money Heist #6",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbZsPMN0WlgI5IKskDuJ2DHcEpGRHjclXbMoE23gK_jaglJm7BlAmG0SdBxdpIefEqPQSL_48bxuS6StDaZgAVtlrl-li3LxMA.png?r=959",
            sortOrder = 84,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-7",
            displayName = "Money Heist #7",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbl7F0njO1GGLokRd_l_HJl8hAOtA1FLsikTPsbsyk82p7jTs_xmWai7lLto1o_pzd5cDztdixXgC3RA4XqGu9Wy5-xGzJFAEg.png?r=b83",
            sortOrder = 85,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-money-heist-8",
            displayName = "Money Heist #8",
            category = "Money Heist",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbMJZT8S6d3BnEzpcTPlmwh13s7_A3QMFp3mqRQZsStQv9GHf4GgmV8rQtpc4vchlkDB0E3xO3SybxI6j5CW1diRam0u8ydjOg.png?r=619",
            sortOrder = 86,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-1",
            displayName = "The Witcher #1",
            category = "The Witcher",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABU4n-VQ3Zbec2VXCWbCGhee047I-10cEyzK6hLbj8mN6s9_2I_olcZ41ZEXvFwToydegaIdGF7AJIS2ChSvO2qls-QHK74U8LA.png?r=c3f",
            sortOrder = 87,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-2",
            displayName = "The Witcher #2",
            category = "The Witcher",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABcudDfq4WJjWMM0IJPr-jsyDI3v11h6w3z_WeGjWhEnZ7NQBcjjZxyTZvF5VGKWZ25Dm7f8e9jaGw0459Uq4NlGcokCYfRa9HA.png?r=d77",
            sortOrder = 88,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-3",
            displayName = "The Witcher #3",
            category = "The Witcher",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRqyaJms_MqkQmqiLp1S4LbMAr7UgFbWSxYs-ZEUdrzaPk8RKfY9MXqcOFFyJL41HOXx73K-a4CHYcvfzZQ7_lgJTOoK8DfllQ.png?r=c53",
            sortOrder = 89,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-4",
            displayName = "The Witcher #4",
            category = "The Witcher",
            storagePath = "https://occ-0-3933-116.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQOZCiH_y_Kx34Pk6LWUXdCd8RTz63obXdX3nFwDEaCdd6fTCyd4M3pgiiQBqI3ttYR9hHGRjjdHp3ZP7vijBpTW_qFfZ8T3tQ.png?r=93c",
            sortOrder = 90,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-5",
            displayName = "The Witcher #5",
            category = "The Witcher",
            storagePath = "https://occ-0-33-37.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABf4WEMS5ZGBiLvuc_N53JgV0C2kwp0Ec9kmmLtxHvxaoRXKxD3msUEJ5_EKTm_eqiZo2f3KDmqH2iOEhxzRzlW2FKur5aQHfqg.png?r=1d8",
            sortOrder = 91,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-6",
            displayName = "The Witcher #6",
            category = "The Witcher",
            storagePath = "https://occ-0-33-37.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfMKXYPcBkBaXwd9XOMXCR1nAiSxYYdsGRun9OlSiD1QS5qZDfcfdQI-5Q6hTM0PNm_2qL9caiCOC-VeJkvwQefPkk_diLjRKg.png?r=fea",
            sortOrder = 92,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-7",
            displayName = "The Witcher #7",
            category = "The Witcher",
            storagePath = "https://occ-0-33-37.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABY3XzBjNxugCUpgSz1TyNkzyXDn98wJlaUP8Bd7zkpYNsJFgoUF3j22XXMNbTDgKZ_1VCR6mjBw34Wp_mVRfnUvh2jh8gru3hg.png?r=ad4",
            sortOrder = 93,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-the-witcher-8",
            displayName = "The Witcher #8",
            category = "The Witcher",
            storagePath = "https://occ-0-33-37.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABeSLTiY-Dgs3DPSDfy178pQyCZk5RUzOoNbB0Sat_lv1drRhAQliQAhC1__HZU_1AlQUbTznKTfxSLg0zZA7nhusTH7RllZz5w.png?r=9b2",
            sortOrder = 94,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-1",
            displayName = "One Piece #1",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABc-963K_PIXK-o0mRr2QiuMS8-Q8HQZWqaRGwtx3mrzM-p23gjyOD-QRxjXtQWgxM2yVp0eKnTKRIW-8J43NWL0xzlEDsoxqOQ.png?r=0a4",
            sortOrder = 95,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-2",
            displayName = "One Piece #2",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABW_3K6JepGxR9Z4R-9XgZDVsgYs7PsTdUHrIsoaB6fuy5EexRESHHvNbMykFjYTzDm_DaIg67Fajuls2Eykp8BF4_fNAXk9B9Q.png?r=396",
            sortOrder = 96,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-3",
            displayName = "One Piece #3",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfsL-kSoIj-SCrh3uYYPjMyJEsf9kwnmCWxaTndO5Cm97v8elwFytcnsD0456DWfD1oNgKawnJhpC8iUisCC8lCgUr1vXMNS5w.png?r=3fc",
            sortOrder = 97,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-4",
            displayName = "One Piece #4",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRNTqBilalwQhyR0IXLrkwl_r0J5pP6F9Z8PfcYfasSv0CpTjQCp8Fp6E15cEJyOe5aWEv4AW7FDazNL4ued20ZP2TNp9fw8Mg.png?r=b69",
            sortOrder = 98,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-5",
            displayName = "One Piece #5",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQRMMX8X7qxycyP5fYtSokmaEUcHp4ZmNzS1qtG4_eSqgoDZuK6MRFyjA-CeXUgxe4flp2ibjdPaBWr5zi01qQP1ElUStZNsEQ.png?r=be0",
            sortOrder = 99,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-6",
            displayName = "One Piece #6",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTxc7dpS6C6YkcEN01dVmTda3IGQUeuNuiRkhv-3OeivfHr8MpBRo5B6sI58Z5jzNeVtBjSAsQ8hTrNj0MQrD301ZDNeDnSPBA.png?r=85b",
            sortOrder = 100,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-7",
            displayName = "One Piece #7",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUSWNXk6qxEFMmWS6e7TqO5JGvuW8FmmtHxVLJlGgdeVnrn6F8TAcVnPqq44npyM02j3EdZjA3Ft9CFiOo_feKGSWMSWpshgyg.png?r=5ca",
            sortOrder = 101,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-one-piece-8",
            displayName = "One Piece #8",
            category = "One Piece",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYu9RaDCGaj3TvJms3c5g6FplYRmmlYMGrktpawzfqx3LxqgUT8l2SNHdSiQH_YueyNrcHusbSlsUCoAilpwK2qnv91V3_jAbg.png?r=6fe",
            sortOrder = 102,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-1",
            displayName = "Black Mirror #1",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUbPc0gMowY4hsJXOFqlD3Rm-CI1OicaxcwRMpVXJd8kpC_JTe4qeRqMuLzU3nfQSGPgYrk5jjl1w4jPuVR2w8ix5dp8_HJSGw.png?r=937",
            sortOrder = 103,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-2",
            displayName = "Black Mirror #2",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSn92t57KQU2TJuYp5fw9SqkT90QVVROUfvY9HzXmWrxYSwV8u1pm-F6h-EiOXAMNXCq8EYgAFyUtPvRC4omGxjmcph6_aKQyA.png?r=2e5",
            sortOrder = 104,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-3",
            displayName = "Black Mirror #3",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABc5i6xIkLNXkZJHbisCMgMaCXsRB8h30xv2M2J6hM8TW3Y4LxadjwAzP-KRmwq6wkBDwFaczonV5X_9jNA3kQeMfpSns24kAIg.png?r=8ff",
            sortOrder = 105,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-4",
            displayName = "Black Mirror #4",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVlbOBvW1x-9mHbkgUJAI25UilbgjfnVaTUDeACcTy7jjnDK0HABdvuclJ580bovJ5dws91jIe_8PNyK14nirRKGX1-xVpjsqA.png?r=eda",
            sortOrder = 106,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-5",
            displayName = "Black Mirror #5",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUbbWSyD8am4It6v93UTuTli0iXw2R27wl2X0hSANaE-_qA3_fZGVAPT3IZzNBW06y_w0y-ust0VkchCV6rVvBWYvUNwR9YpeA.png?r=00c",
            sortOrder = 107,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-6",
            displayName = "Black Mirror #6",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABexs0Rv9k7I3rE-pvPFrvfLnZpgzW1gw2jeRcKli05n7J-hpm4C1PCrpb0MZVJD73znbOhQvpQPPgeGeQ2AmGFA3IGPHEZdDhA.png?r=8d9",
            sortOrder = 108,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-7",
            displayName = "Black Mirror #7",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZ0u6MKo5D-r0q3bz3MpLoeW83v1TcPKw7GhAHuXn_wnQb9_ZMHCOvY1ra322g_n00WeX3ojQkRYiKLgMDXx3S88nmUtxUQw6Q.png?r=19c",
            sortOrder = 109,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-black-mirror-8",
            displayName = "Black Mirror #8",
            category = "Black Mirror",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVfRng_a6tvvynIfXPdDYDAr9QAFt6xSspWHi1sS53iTZC-MZxmhBWa9Pjp_l1Gtg_eM9eTtIEPGzLZPItqRT_YbB3EWdrY7Aw.png?r=287",
            sortOrder = 110,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-1",
            displayName = "Cobra Kai #1",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbf1Je6RPt-8wyDbofj5cDcwPNUN91C-CwkJ7QY5Vm-601p4Jc9064Boj4ZeSaccIKPCxnEIVmK4Me-lbl9RMcObivfCH6OaIQ.png?r=3d0",
            sortOrder = 111,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-2",
            displayName = "Cobra Kai #2",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABdB9v64CRzxfUM3QepfzggrzgbDcv8YQeWqyz62qNq38aQzE4pGR-p2C6alcw2FwU6kfVguOdKG_yrI48F1qgirYBbcqd0ns8A.png?r=9e0",
            sortOrder = 112,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-3",
            displayName = "Cobra Kai #3",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABaGuapFk9F338XTq0SsG1nMcMaeJHdGwQaVO1iFgdc1fIfbpIMuhQwkAKz1xowA9Xwxovw1BORGGyixyMa_K7hgRGHUo4fHd7g.png?r=46d",
            sortOrder = 113,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-4",
            displayName = "Cobra Kai #4",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYDIHW3jl7NSlZS4pD6Y7aLZYc0W6dA1iD8GIODM0CQLNTr9Y7-aMygz-2-JrCyYedZkdPP8js3DiF_YHMofcn7um8VwCvDU2Q.png?r=796",
            sortOrder = 114,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-5",
            displayName = "Cobra Kai #5",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABcBTrvO03g3CLDkOIsITRykQmzsiV_YLssP8lW35YYZSjQSgkxZSvBxczFWdwbAW4TboibPUP4u90QbaSWqh8ITCvZvCGGNA5A.png?r=ec0",
            sortOrder = 115,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-6",
            displayName = "Cobra Kai #6",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZNS9o3ttZ8VAQYE67jBdK30WpOZBjVSoJq8OXAYbVNlb_vtf-K-Sg9uQTHufX_19RTr8jqNfRZzxotl32mTXfjCQqKcLTtAlw.png?r=41f",
            sortOrder = 116,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-7",
            displayName = "Cobra Kai #7",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABU5aYJodyKQke8YdsUfSZX4I3UugTfcD_iUiNac_7kVYDOEal9Jjss5B0qYmRTkKO03buoIe6JCz840TOzV21d-imShkz5tCEg.png?r=fe8",
            sortOrder = 117,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-cobra-kai-8",
            displayName = "Cobra Kai #8",
            category = "Cobra Kai",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQPiju7JxdcTXdE2cff4Hogbv2jzWdzDzVJHZtZB-z89sUTnrGvE2c1xJUd-gobQcz-F4xdzFTmboGqrYlnjWCcWFnYZ6aBVmQ.png?r=721",
            sortOrder = 118,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bojack-horseman-1",
            displayName = "BoJack Horseman #1",
            category = "BoJack Horseman",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQc_OpyzMxJfS-uNYi1u2qrrzQJRfBddqyyrn9GsJIygOLiY3Zg93eeyY2LIn8SN9lu4Q_hGGvEhjwrAvAE0OCtZFvcj_wC5gA.png?r=3e2",
            sortOrder = 119,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bojack-horseman-2",
            displayName = "BoJack Horseman #2",
            category = "BoJack Horseman",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABbcNwfOQR4OQPtplYFAnsu4MVme3gZPJp8NppLzrK4vxA4m75-13GmBVbmXltHMRvI3mncXQddWLCPtY8dditHMW1Z3FjYrd2Q.png?r=652",
            sortOrder = 120,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bojack-horseman-3",
            displayName = "BoJack Horseman #3",
            category = "BoJack Horseman",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABVT0bCqXEGylNSPyZhCiHsbS4FhlB3qU3XfuIM4hcCqYAH1e6HbCgTAT1JJyvsulM30A5pRN93lyDiPEbQca0exMLGOKoQ7zBA.png?r=c5e",
            sortOrder = 121,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bojack-horseman-4",
            displayName = "BoJack Horseman #4",
            category = "BoJack Horseman",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSjchj8mrkUsyibCbeDdvMZqjPZpfIs04XDYop0OHdsFQs51zIMgqqHcTMiYCRYy4ZxDdB-p9U2TyqJWdjeYUjbI5qPDN6U6tg.png?r=181",
            sortOrder = 122,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bojack-horseman-5",
            displayName = "BoJack Horseman #5",
            category = "BoJack Horseman",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRpqDJLlMCUlEwtPdo7mZAUleZjNXbKmpZtBVZUVz8P2kNZfoOcYivVg5gyZiQGc3YKhdK3A396WexmwmzWcWC5afRjZ5yVnyg.png?r=379",
            sortOrder = 123,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-1",
            displayName = "Dark #1",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABU2x9ED3H5k_2uuu_TjFHONsuvCDfEpZcaeV0qRIcFZ2acADMeGqBl1riq-qzmqH6ycnXPj-GbD5woYfLcwZ--SaguMrhBypmQ.png?r=805",
            sortOrder = 124,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-2",
            displayName = "Dark #2",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABatLjcqhvIUw4ChV9plA_YlRQPOkCC5EbRDx1I0hc2rDxLvX8G0ZVIpGqxwLv7RP2XXeArmMZx9xHashfPpiEL3Dh6IC4871wA.png?r=5f8",
            sortOrder = 125,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-3",
            displayName = "Dark #3",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXJmhBVuzHTysTZV2R883Fyld66wZcakW-xNMZAvbUdf1ly6WO6Vv9scygtVc-TSJ1yHcczAFu6u-TwdxOyPZE8r4kNJBo2WQg.png?r=e21",
            sortOrder = 126,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-4",
            displayName = "Dark #4",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSQLJqox55xK4opN91mD9O2Gc5AzG5UF4XPqJTewZvhhIZEdGy7Toa3dGwUZ08D9uICwgGu0f564PT_vlVvdAVyQVfNDtlfQfQ.png?r=eae",
            sortOrder = 127,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-5",
            displayName = "Dark #5",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUlXX9WUam7Ef0DiErx18Bk9XRKM7COFP6YZKAew1K1pwflO2FxEBA_VVNHBnrdV7OdBHe7FQkqMEOQTrWnil0DjqQtzYlaKUw.png?r=9ce",
            sortOrder = 128,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-6",
            displayName = "Dark #6",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQKdfWzyRyVPYbkNK6asgCmvHnAX0Vs9AC4KQseligIVZIkfS6sNvG-kvQFW0cE5v8KJusLWSftahSVEDpaWalsL02P8LrpCWw.png?r=abc",
            sortOrder = 129,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-7",
            displayName = "Dark #7",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfwjf-g-ZMTfp7hyi-KAxb5o2Q59aqiTSduLLIuV-n3yatMfZtinAUOzI5aoTZyAaEUFLQlPbQN3Yc5zJdbxR5bN4-p-4iNFjg.png?r=cec",
            sortOrder = 130,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-dark-8",
            displayName = "Dark #8",
            category = "Dark",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABfLA79bNHYcRWtRv42gtPsvDDUKl97EUxnR_ahdZDvhhzuTCIdk-LtUpCjtH2MgoWL0GNuheSfn2oCxh1KvbdKSkBJapZPCDKA.png?r=dca",
            sortOrder = 131,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-1",
            displayName = "Sex Education #1",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABdxTFxA39oFAAxq7QvV2eP8sXlxUvpefjF37BzwcNWNX1T0eIOwoXuh3wsmi9s2Ekio0_ghfw83JC1sd3EYary99EIW9DobKHg.png?r=758",
            sortOrder = 132,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-2",
            displayName = "Sex Education #2",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQMY6lyidq6COq24lA9VSOqRMoIG5yv4iVk5E2GaTylA8ay2tH8Vuzd5SNMlMOV6hj6eES4CiVbd9YNQyu8fU5XsYzNRa04t3Q.png?r=4ec",
            sortOrder = 133,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-3",
            displayName = "Sex Education #3",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABT-IA4FjTxxzNmM1Bx-Wa6H1jQooqySeCUhoUe_ik1GangQp2D7ul7PNMrqnIBOAvfHZuWORs5QoQId7Dx5YPP_asSOeAzgCqg.png?r=ebd",
            sortOrder = 134,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-4",
            displayName = "Sex Education #4",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABd8bLEI8iuUFmIitmlRBuOomIKjflKX4tyEh64QujY4bdISels_X4Oejv2AiZe2US3n0oK2RSbu8T-G6MPBoSaqNHqZgCu-4pA.png?r=a6e",
            sortOrder = 135,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-5",
            displayName = "Sex Education #5",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWm8V3BFnP7XTxeFtG0WCrqs28I14SxpuAJgqHNfyfQsuT9A93p0UDX7uTIk67j7oLQXEXEaxRqPjNaCGxsO__3Pneg23rxfeg.png?r=540",
            sortOrder = 136,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-6",
            displayName = "Sex Education #6",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABc0QiYTGb9V_y5OMrXaRBwHteWkcQTaEu3DhpMfmzBh_qixo1-vREcEsYJt9itrx-f0CFF2ik6UtjTSNuK_WKNWTEBu1M11cKQ.png?r=1e6",
            sortOrder = 137,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-7",
            displayName = "Sex Education #7",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABXjuqL19WMyPtMBDVYYSkgzUGXrOohZEODCp4k8hjvE3vVfKJC7jdXTzxU48vnzSpsUJw5mlBUGNTATt6nBHo6BnirQ_wnFlsg.png?r=27f",
            sortOrder = 138,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-sex-education-8",
            displayName = "Sex Education #8",
            category = "Sex Education",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABZFZlOGnj5GZxKyz5XiJSHGlvzrzaLulR0brMEtbRW_Oq4lOy8T6RTsd6rV9E3blF0LbMQuielVB28UzvLrsfNeNtbHLv6gZKA.png?r=1c8",
            sortOrder = 139,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-1",
            displayName = "Bridgerton #1",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSIlxASbcJeSHIU2OBytZz1k18MlqnD6ynU4F6T3FNi-V7mNE3EpQAPtaFwCwT9vI7CmjgNuECeVAR_zibH6yHHlZNMRwdPPAA.png?r=ab2",
            sortOrder = 140,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-2",
            displayName = "Bridgerton #2",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABeYF9COjNQ7aUsafKCNVGJQrRM7RfNBHnpH3h2z-a-0_sGeISuEllbUOnIEvm2l70C7xPHCN6RdCJ5SrTD_Waz65GvYIDK6-mA.png?r=f14",
            sortOrder = 141,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-3",
            displayName = "Bridgerton #3",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRkgs5M_UImziJLj-1IBdVc9tKjCRFIJEmnsc6zuWUE4zwJjxgchOcMYbkTmDPBzgJJDoXIga-Czy3WxNs3UUUxKz9PoWxh-Ig.png?r=822",
            sortOrder = 142,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-4",
            displayName = "Bridgerton #4",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABedjQlhlbQ8woQpVYlid12sMSjmmlVmPaj8hVp313B5lyabjXEQyppMAOozdYi_7Bqlv5N8YbEg9FytFEJIuYu-oiAMI8dYS4w.png?r=893",
            sortOrder = 143,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-5",
            displayName = "Bridgerton #5",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABahPZ2VjPq33kQyxiIqluegDn-f16A96zmYR52OZ9-k7ubd7gAbYJZCQVDj0q-_3rz2H1rC53Ss4Y6RwryE4eUHllpcv2BnhtA.png?r=39e",
            sortOrder = 144,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-6",
            displayName = "Bridgerton #6",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABTSir-CPcz6U35DGgb8zq3d-dTnJTyi9w3FwuhvxJYvHxgs7ci41lWHmQczLTaPyFNBdcrk_JEQl1SQtIaT6AwY6yQjl67mMYg.png?r=9b6",
            sortOrder = 145,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-7",
            displayName = "Bridgerton #7",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABahQrbzJ3CRwznAN6m4e3N58amPWcMa84g2Xyq9T2cMTIrzub-j3Z-wE9YY8JWuFXlGUTYXwhGnpJXZ9NxEntTQBwoTVmhi6rg.png?r=8a3",
            sortOrder = 146,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-bridgerton-8",
            displayName = "Bridgerton #8",
            category = "Bridgerton",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABag9yO_LX58Nm1us8DLTWWH5pkGvxnSCHF9fPN4AIxeSWun5c2Yfbpkitqo7uTMoTX-Q_B5UIUL3q-K9NTew2c5n0U87341Kzg.png?r=ba2",
            sortOrder = 147,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-1",
            displayName = "Heartstopper #1",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSq8XhpQv84VZzeyAHEV4URKyY2P7kOlY6Db3IaIs1hEIb5HvV8bBSwflQzZuzvfflVpgYwaCfd2sKZe_hM3V2s5VUb3FXRl2Q.png?r=677",
            sortOrder = 148,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-2",
            displayName = "Heartstopper #2",
            category = "Heartstopper",
            storagePath = "https://occ-0-3467-1432.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQvoUtZG1zLUug4Acnao5lC4FoJTgFq96bS4XY4QVDLgTpHn_8OefZnoACBL84QT8q1im9eGmvENFOQdWMNyzxMd-0zA-c0reQ.png?r=749",
            sortOrder = 149,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-3",
            displayName = "Heartstopper #3",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABWkm8khBDQnulhoA9mxgTlElJmFvfj64pnzDqAfR5vrhPW0bREp7_5AO_GIJ1yO3jaG8MGEkYbnRJ1-hldFKmbJ6eVv9NNv1pQ.png?r=f4c",
            sortOrder = 150,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-4",
            displayName = "Heartstopper #4",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABUglyX33ZqK3UB97xZ_e88eqORYMccr-bnVgAsDoSHdSDCXyOu5jFaJqrfLq2FQITWJE2lrO3W9XwkV6qLiwQP3EY-bVBQoJTg.png?r=107",
            sortOrder = 151,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-5",
            displayName = "Heartstopper #5",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABQjkMPvwZIRnIuwIBXtS7gKuUNuKnx1tqag-md5ohO4X1bhrAFllvRO0o3BIqgzFv1iNfptKw1mHOT_cYuLCqCm5Wqia8a2S2A.png?r=28a",
            sortOrder = 152,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-6",
            displayName = "Heartstopper #6",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABRZiR4q_YoBSB5XOMQyyflTzl6Iutuz0_nkLo_odPhvid_HUJjxJU5u1cn-Ahx_LeeOpX7t83rySnAnpBg1GKab6D7AXJdUzkw.png?r=454",
            sortOrder = 153,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-7",
            displayName = "Heartstopper #7",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABSvnHoGs5cUBSikVQGXKfwZ2zQisRq7__CjKZ8euema20KSgdqYH4QlCbNHLGWYF6_zRmcZm4OzNUHEsUCVBZHwqdCwzqCg0Pw.png?r=4a1",
            sortOrder = 154,
            isActive = true,
            bgColor = "#141414",
        ),
        AvatarCatalogItem(
            id = "netflix-heartstopper-8",
            displayName = "Heartstopper #8",
            category = "Heartstopper",
            storagePath = "https://occ-0-8782-2219.1.nflxso.net/dnm/api/v6/vN7bi_My87NPKvsBoib006Llxzg/AAAABYAkRwU15AhuOPwb1d0_oU-oOU460F6RpiDhMED43RUZQ_wClYABDXE4vYgl_6__wY9aA6Do9fwkeqMFz8B07Jy_MXebFrhORQ.png?r=c73",
            sortOrder = 155,
            isActive = true,
            bgColor = "#141414",
        ),
    )
}
